#!/bin/bash

# make bash behave
set -euxo pipefail

# this script needs root to install packages
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

# given we might cherry-pick a fix to older releases, setup git to be able to commit
git config --global user.email "citusbot@citusdata.com"
git config --global user.name "citus bot"

# read pg major version, error if not provided
PG_MAJOR=${PG_MAJOR:?please provide the postgres major version}

CITUS_VERSIONS=${CITUS_VERSIONS:?please provide CITUS_VERSIONS to package in upgrade container }

# install old citus versions
for citus_version in ${CITUS_VERSIONS}
do
  git clone --branch $citus_version https://github.com/citusdata/citus.git /citus_$citus_version
done

basedir="$(pwd)"

build_ext() {
  pg_major="$1"
  citus_version="$2"
  citus_dir=/citus_$citus_version

  builddir="${basedir}/build-${pg_major}"

  # do everything in a subdirectory to avoid clutter in current directory
  mkdir -p "${builddir}" && cd "${builddir}"

  CFLAGS=-Werror "${citus_dir}/configure" PG_CONFIG="/usr/lib/postgresql/${pg_major}/bin/pg_config" --enable-coverage

  pushd ${citus_dir}
  # cherry-pick gcc10 fix if not already on the branch cherry-pick locally
  if ! git merge-base --is-ancestor b8dd8f50d19a98e5d8ce355947d72a01c028c8b3 HEAD ; then
    git cherry-pick b8dd8f50d19a98e5d8ce355947d72a01c028c8b3
  fi
  popd

  installdir="${builddir}/install"
  make -sj$(nproc) && mkdir -p "${installdir}" && make DESTDIR="${installdir}" install

  cd "${installdir}" && find . -type f -print > "${builddir}/files.lst"
  tar cvf "${basedir}/install-pg${pg_major}-citus${citus_version}.tar" `cat ${builddir}/files.lst`
  find usr/lib/postgresql/${pg_major}/lib -type f -name '*.so' -printf '%P\n' > "${builddir}/so-files.lst"
  tar cvf "${basedir}/so-pg${pg_major}-citus${citus_version}.tar" -C usr/lib/postgresql/${pg_major}/lib -T "${builddir}/so-files.lst"
  cd "${builddir}" && rm -rf install files.lst && make clean
}
for citus_version in ${CITUS_VERSIONS}
do 
  build_ext "$PG_MAJOR" "${citus_version}"
done

chmod o+w -R /usr/

# keep that image size small!
echo "Cleaning up..." >&2
rm -rf /var/lib/apt/lists/*
