#!/bin/bash

# make bash behave
set -euxo pipefail
IFS=$'\n\t'

# this script needs root to install packages
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

# taken from https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -o|--citus-pre-tar)
    CITUS_PRE_TAR="$2"
    shift # pass argument
    shift # pass value
    ;;   
    -t|--target)
    TARGET="$2"
    shift # pass argument
    shift # pass value
    ;;    
    *) # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;    
esac
done

# Take Makefile.global from already made build
cp  ${CIRCLE_WORKING_DIRECTORY}/build-$PG_MAJOR/Makefile.global ${CIRCLE_WORKING_DIRECTORY}
status=0

gosu circleci make -C "${CIRCLE_WORKING_DIRECTORY}/src/test/regress" $TARGET bindir=/usr/lib/postgresql/$PG_MAJOR/bin citus-pre-tar=$CITUS_PRE_TAR citus-post-tar=/home/circleci/project/install-$PG_MAJOR.tar || status=$?

diffs="${CIRCLE_WORKING_DIRECTORY}/src/test/regress/regression.diffs"

if test -f "${diffs}"; then cat "${diffs}"; fi

exit $status