#!/bin/bash

# make bash behave
set -euxo pipefail
IFS=$'\n\t'

# this script needs root to install packages
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

# get codename from release file
. /etc/os-release
codename=${VERSION#*(}
codename=${codename%)*}

pg_latest=13

# explicitly set user/group IDs
groupadd -r circleci --gid=1729
useradd -mg circleci --uid=1729 --shell=/bin/bash circleci

echo "Running apt-get update..." >&2
apt-get update
apt-get install -y --no-install-recommends \
  apt-transport-https \
  ca-certificates \
  curl \
  debian-archive-keyring \
  gnupg

# import key and keep apt-key from issuing warnings
echo "Importing PGDG key..." >&2
curl -sf https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -

# add pgdg repo to sources
echo "Writing /etc/apt/sources.list.d/pgdg.list..." >&2
echo "deb http://apt.postgresql.org/pub/repos/apt/ ${codename}-pgdg main ${pg_latest}" > \
     /etc/apt/sources.list.d/pgdg.list  

echo "Installing tools for testing PostgreSQL extensions..." >&2
apt-get update && apt-get install -y --no-install-recommends make postgresql-common \
 perl libcurl3 "postgresql-${PG_MAJOR}" "postgresql-server-dev-${PG_MAJOR}"
 
# we need autoconf and build-essential for running the tests
# we need other libraries for configure to pass, even though we could use
# --without-libcurl while configuring, we prefer this for now. 
apt-get install -y autoconf build-essential libcurl4-openssl-dev \
 libicu-dev libreadline-dev libselinux1-dev libxslt-dev libssl-dev 


echo "Installing tools for failure testing..." >&2
pip3 install -Ir /tmp/etc/requirements.txt

# Give permission for usr so that circleci can write citus artifacts
chmod o+w -R /usr/

# install gosu so that we can run tests from root with circleci user
apt-get install -y gosu


# keep that image size small!
echo "Cleaning up..." >&2
rm -rf /var/lib/apt/lists/*
