version: 2
updates:
  - package-ecosystem: pip
    directory: "/circleci/images/citusupgradetester/files/etc"
    schedule:
      interval: weekly
      day: sunday
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 0

  - package-ecosystem: pip
    directory: "/circleci/images/failtester/files/etc"
    schedule:
      interval: weekly
      day: sunday
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 0

  - package-ecosystem: pip
    directory: "/circleci/images/pgupgradetester/files/etc"
    schedule:
      interval: weekly
      day: sunday
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 0

  - package-ecosystem: pip
    directory: "/circleci/images/stylechecker/files/etc"
    schedule:
      interval: weekly
      day: sunday
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 0
