name: build-test-images
env:
  DOCKERHUB_USER_NAME: ${{ secrets.DOCKERHUB_USER_NAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  MAIN_BRANCH_NAME: master
on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build_dev_images:
    if: github.ref_name != 'master'
    name: push-test-images-for-dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - extbuilder
          - exttester
          - failtester
          - citusupgradetester
          - pgupgradetester

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # If current branch is not master,build and publish dev image
      - name: Build & Push all dev images
        run: |
          cd circleci/images
          make push-${{ matrix.command }}-all

  build_release_images:
    if: github.ref_name == 'master'
    name: push-test-images-for-release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      # If current branch is not ,build and publish live image
      - name: Build & Push all live images
        if: ${{github.ref_name == env.MAIN_BRANCH_NAME }}
        run: |
          cd circleci/images
          RELEASE=1 make push-all
